apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-dev
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/timeout: 2m
    creationTimestamp: null
    labels:
      app: prov-app
      component: prov-app
      env: dev
      template: component-route-template
    name: prov-app
  spec:
    host: prov-app-dev${OPENSHIFT_APPS_BASEDOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: prov-app
      weight: 100
    wildcardPolicy: None
parameters:
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
