:toc: macro

= Provisioning App: Internal architecture / Development

toc::[]

The Project is based on Spring Boot, using several technologies which can be seen in the https://github.com/opendevstack/ods-provisioning-app/blob/master/build.gradle[build.gradle].

The provision app is merely an orchestrator that does HTTP REST calls to Atlassian Crowd, Jira, Confluence, Bitbucket and
Jenkins (for openshift interaction).

The APIs exposed for direct usage, and also for the UI are in the https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/controller[controller package].
The connectors to the various tools to create resources are in the https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/services[services package]

== How to develop locally
. Make sure that you have installed GIT and JAVA ( >= 8 ).
. Clone the project out of Github

```
$ git clone https://github.com/opendevstack/ods-provisioning-app.git
```

[arabic, start=3]
. Change directory into ods-provisioning-app

```
$ cd ods-provisioning-app
```

[arabic, start=4]
. If you want to build / run locally - create `gradle.properties` in the project's root to configure connectivity to OpenDevStack NEXUS

[source,properties]
----
nexus_url=<NEXUS HOST>
nexus_user=<NEXUS USER>
nexus_pw=<NEXUS_PW>
----

If you want to build / run locally without NEXUS, you can disable NEXUS by adding the following property to `gradle.properties`:

[source,properties]
----
no_nexus=true
----

Alternatively, you can also configure the build using environment variables:

|===
| Gradle property | Environment variable

| nexus_url
| NEXUS_HOST

| nexus_user
| NEXUS_USERNAME

| nexus_pw
| NEXUS_PASSWORD

| no_nexus
| NO_NEXUS
|===

[arabic, start=5]
. You can start the application with the following command:

[source,bash]
----
# to run the server execute
./gradlew bootRun
----

To overwrite the provided https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/resources/application.properties[application.properties] a configmap is created out of them and injected into /config/application.properties within the container.
The base configuration map as well as the deployment yamls can be found in https://github.com/opendevstack/ods-provisioning-app/blob/master/ocp-config/prov-app/cm.yml[ocp-config], and overwrite parameters from application.

[arabic, start=6]
. After started the server it can be reached in the browser under

```
http://localhost:8080
```

== How to deploy to OpenShift

In order to test your changes in a real environment, you should deploy the provisioning app in OpenShift. To do so, you need to have an existing OpeDevStack project (consisting of `-dev`, `-test` and `-cd` namespaces). If you don't have one yet, you can xref:provisioning-app:index.adoc#_basic_idea_usage[create one via the provisioning app in the central namespace].

Now you can make use of the https://github.com/opendevstack/ods-quickstarters/tree/master/ods-provisioning-app[ods-provisioning-app quickstarter] in order to set up the Bitbucket repository in your Bitbucket space. The easiest way to provision that quickstarter is via https://github.com/BIX-Digital/ods-contrib/tree/master/quickstart-with-jenkins. Once you have provisioned the quickstarter, the first deployment of the prov app will run, but fail since you need to create the OpenShift resources manually. This step cannot be automated during the quickstart process at the moment as you need to supply configuration manually. Once the resources have been created, subsequent runs of the Jenkins pipeline should succeed and deploy the prov app in your own ODS project.

== Frontend Code

The frontend is based on jquery and thymeleaf. All https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/resources/static/js/client.js[posting to the API] happens out of java script (client.js)

== Backend Code

The backend is based on Spring Boot, authenticates against Atlassian Crowd (Using property `provision.auth.provider=crowd`) or OAUTH2/OpenID Connect provider (Using property `provision.auth.provider=oauth2`) and exposes consumable APIs (`api/v2/project`).
Storage of created projects happens on the filesystem thru the https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/storage/LocalStorage.java[StorageAdapter].
Both frontend (html) and backend are tested thru Junit & Mockito

== Authentication Implementation
By using the property `provision.auth.provider=crowd` or `provision.auth.provider=oauth2`, the application uses eigher CROWD or OAUTH2 authentication. Dependent of the property used, different spring beans are used for configuration.
The switch between the two options is implemented via Spring's _ConditionalOnProperty_ annotation.

CROWD - specific configuration classes are located in the java package _org.opendevstack.provision.authentication.crowd_.

Example:
[source%nowrap,java]
.org.opendevstack.provision.authentication.crowd.CrowdSecurityConfiguration.java
----
@Configuration
@EnableWebSecurity
@EnableCaching
@EnableEncryptableProperties
@ConditionalOnProperty(name = "provision.auth.provider", havingValue = "crowd")
public class CrowdSecurityConfiguration extends WebSecurityConfigurerAdapter {
//...
}
----

OAUTH2 - specific configuration classes are located in the java package _org.opendevstack.provision.authentication.oauth2_.

Example:
[source%nowrap,java]
.org.opendevstack.provision.authentication.oauth2.Oauth2SecurityConfiguration.java
----
@Configuration
@Order(Ordered.HIGHEST_PRECEDENCE)
@ConditionalOnProperty(name = "provision.auth.provider", havingValue = "oauth2")
@EnableWebSecurity
@EnableOAuth2Client
public class Oauth2SecurityConfiguration extends WebSecurityConfigurerAdapter {
//...
}
----

== Consuming REST APIs in Java

Generally this is a pain. To ease development, a few tools are in use:

* Jackson (see link below)
* OKTTP3 Client (see link below)
* jsonschema2pojo generator (see link below)

The process for new operations to be called is:

. Look up the API call that you intend to make
. see if there is a JSON Schema available
. Generate (a) Pojo('s) for the Endpoint
. Use the pojo to build your request, convert it to JSON with Jackson and send it via OKHTTP3, and the Provision Application's https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/util/rest/RestClient.java[RestClient]

== Consuming REST APIs via curl

[source,bash]
----
PROVISION_API_HOST=<host name>

curl -D headers.txt -k -H "Content-Type: application/x-www-form-urlencoded" \
-X POST ${PROVISION_API_HOST}/j_security_check \
-d username=<username> -d password=<password>

# grab the login status, and exit if error
login_status=$(cat headers.txt | grep ${PROVISION_API_HOST}/login?error)

if [[ $login_status != "" ]]; then echo "Login Error"; exit 1; fi;

# grab the needed IDs and bake the cookies
JSESSION_ID=$(cat headers.txt | grep "Set-Cookie: JSESSION" | cut -d ';' -f1 | cut -d ":" -f2)";"
CROWD_COOKIE=$(cat headers.txt | grep "Set-Cookie: crowd" | cut -d ';' -f1 | cut -d ":" -f2)

COOKIES=${JSESSION_ID}${CROWD_COOKIE}

# sample provision file >> create.txt
{
  "name" : "<Mandatory name>",
  "key" : "<Mandatory key>",
  "createpermissionset" : true,
  "jiraconfluencespace" : true,
  "admin" : "<admin user>",
  "adminGroup" : "<admin group>",
  "userGroup" : "<user group>",
  "readonlyGroup" : "<readonly group>",
  "openshiftproject" : false
}

provisionfile=create.txt

# invoke the provision API to create a new project
curl -k -X POST --cookie "$COOKIES" -d @"$provisionfile" \
-H "Content-Type: application/json; charset=utf-8" -v ${PROVISION_API_HOST}/api/v2/project
----


== Link collection

* http://www.mkyong.com/spring-boot/spring-boot-spring-security-thymeleaf-example/[Mkyong spring boot + security + thymeleaf example]
* http://www.webjars.org/[Getting more Webjars]
* http://www.jsonschema2pojo.org/[Generating POJOs from JSON Schemas] very helpful for the Atlassian API Docs
* https://square.github.io/okhttp[OKHttp3]
* https://site.mockito.org[Mockito]
* https://github.com/FasterXML/jackson[Jackson]

*Atlassian API's*

* https://docs.atlassian.com/jira/REST/server/#api/2/fullJiraProject-createProject[Jira API]
* https://docs.atlassian.com/ConfluenceServer/rest/6.12.1/[Confluence API]
* https://developer.atlassian.com/server/bitbucket/reference/rest-api/[Bitbucket API]
* https://developer.atlassian.com/server/crowd/crowd-rest-apis/[Crowd API]
