apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    labels:
      app: jenkins
    name: jenkins_edit
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: prov-cd
  userNames:
  - system:serviceaccount:prov-cd:jenkins
