apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: jenkins
    name: jenkins
  spec:
    host: jenkins-${TAILOR_NAMESPACE}${OPENSHIFT_APPS_BASEDOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: jenkins
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: jenkins
    name: webhook-proxy
  spec:
    host: webhook-proxy-${TAILOR_NAMESPACE}${OPENSHIFT_APPS_BASEDOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: webhook-proxy
      weight: 100
    wildcardPolicy: None
parameters:
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
- name: TAILOR_NAMESPACE
  required: true
