apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  data:
    password: ${CD_USER_PWD_B64}
    username: ${CD_USER_ID_B64}
  kind: Secret
  metadata:
    labels:
      app: jenkins
    name: cd-user-with-password
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    auth-token: ${SONAR_AUTH_TOKEN_B64}
  kind: Secret
  metadata:
    annotations: {}
    creationTimestamp: null
    name: sonarqube
    labels:
      app: jenkins
  type: opaque
- apiVersion: v1
  data:
    password: ${NEXUS_PASSWORD_B64}
  kind: Secret
  metadata:
    annotations: {}
    creationTimestamp: null
    name: nexus
    labels:
      app: jenkins
  type: opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: webhook-proxy
    labels:
      app: jenkins
  type: opaque
  data:
    trigger-secret: ${PIPELINE_TRIGGER_SECRET_B64}
parameters:
- name: CD_USER_ID_B64
  required: true
- name: CD_USER_PWD_B64
  required: true
- name: SONAR_AUTH_TOKEN_B64
  required: true
- name: NEXUS_PASSWORD_B64
  required: true
- name: PIPELINE_TRIGGER_SECRET_B64
  required: true
