apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  data:
    password: ${CD_USER_PWD}
    username: ${CD_USER_ID}
  kind: Secret
  metadata:
    labels:
      app: jenkins
    name: cd-user-with-password
  type: kubernetes.io/basic-auth
- apiVersion: v1
  data:
    auth-token: ${SONAR_SERVER_AUTH_TOKEN}
  kind: Secret
  metadata:
    annotations: {}
    creationTimestamp: null
    name: sonarqube
    labels:
      app: jenkins
  type: opaque
- apiVersion: v1
  data:
    password: ${NEXUS_PASSWORD}
  kind: Secret
  metadata:
    annotations: {}
    creationTimestamp: null
    name: nexus
    labels:
      app: jenkins
  type: opaque
- apiVersion: v1
  kind: Secret
  metadata:
    name: webhook-proxy
    labels:
      app: jenkins
  type: opaque
  data:
    trigger-secret: ${PIPELINE_TRIGGER_SECRET}
parameters:
- name: CD_USER_ID
  required: true
- name: CD_USER_PWD
  required: true
- name: SONAR_SERVER_AUTH_TOKEN
  required: true
- name: NEXUS_PASSWORD
  required: true
- name: PIPELINE_TRIGGER_SECRET
  required: true
