== Configuration Guide

The Provisioning Application is configured via spring boot profiles.
Default configuration properties are definded in https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/resources/application.properties[application.properties]

=== Authentication Configuration
There are to separate authentication options to authenticated a user for the provisioning app.

* CROWD (default)
* OAUTH2

:tip-caption: pass:[&#128161;]
[TIP]
Note that the current OAUTH2 implementation is only used for authentication the user to the provisioning app.
To authentication that is used for the REST - API calls of Atlassian Crowd, Jira, Confluence, Bitbucket and Rundeck is done eighter via the logged in uses credentials (user name and password) or via the technical users, that are configured in the used spring boot profile.


==== Authentication Crowd Configuration

[source%nowrap,bash]
.application.properties
----
provision.auth.provider=crowd # <1>
spring.profiles.active=crowd # <2>
----
<1> configures crowd authentication provider
<2> include crowd profile per default.

The crowd specific configuration is done in the included profile _crowd_, see property documentation inside the profile file _application-crowd.properties_. The provided example configuration is appropriate for a locally installed OpenDevStack environment.

==== Authentication OAUTH2 Configuration
A default oauth2 configuration is given in spring boot profile https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/resources/application-outh2.properties[application-oauth2.properties]. The provided example configuration is appropriate for a locally installed OpenDevStack environment, when the _idmanager_ vagrant box is used.

[source%nowrap,bash]
.application-oauth2.properties
----
provision.auth.provider=oauth2 # <1>

idmanager.url=http://192.168.56.32:8080 # <2>
idmanager.realm=provisioning-app #<3>

oauth2.user.roles.jsonpointerexpression=/claims/roles # <4>

# <5>
spring.security.oauth2.client.registration.keycloak.client-id=ods-provisioning-app
spring.security.oauth2.client.registration.keycloak.client-secret=put-your-secret-here
spring.security.oauth2.client.registration.keycloak.clientName=ods-provisioning-app
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirectUri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.keycloak.scope=openid

# <6>
spring.security.oauth2.client.provider.keycloak.authorization-uri=${idmanager.url}/auth/realms/${idmanager.realm}-app/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=${idmanager.url}/auth/realms/${idmanager.realm}/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=${idmanager.url}/auth/realms/${idmanager.realm}/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=${idmanager.url}/auth/realms/${idmanager.realm}/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

----
<1> configures oauth2 authentication provider
<2> URL to idmanager. The value defaults to opendevstack idmanager box with keycloak installation
<3> Name of realm that is used
<4> The application reads the user roles from the claim that is inside the oauth2 ID-Token. The property _oauth2.user.roles.jsonpointerexpression_ is a JsonPointer - Expression that defines a path to the roles that are extracted from the id token. Details regarding pointer expression can be found at https://github.com/opendevstack/ods-provisioning-app/blob/master/https://fasterxml.github.io/jackson-core/javadoc/2.5/com/fasterxml/jackson/core/JsonPointer.html[Jackson-core JsonPointer Documentation]
<5> Defines the OAUTH2 client registration properties, in particular the client name and client secret. See
https://github.com/opendevstack/ods-provisioning-app/blob/master/https://docs.spring.io/spring-security/site/docs/5.1.5.RELEASE/reference/html/jc.html#oauth2login-boot-property-mappings[OAUTH2 Spring Boot 2.x Property Mappings] for details.
<6> Defines the OAUTH2 _client.provider_ properties. These properties correspond to the _well-known_ OAUTH2-URIs. In case of keycloak, this URIs can be read out using the  https://github.com/opendevstack/ods-provisioning-app/blob/master/http://192.168.56.32:8080/auth/realms/provisioning-app/.well-known/openid-configuration[.well-known/openid-configuration-link]

==== Authentication to third party apps via technical users
The rest api calles use HTTP _basic access authentication_ to communicate with Jira, Confluence, Bitbucket and Rundeck. The used credentials are read from a pair of properties. For Example, _rundeck.admin_password_ and _rundeck.admin_user_ properties are used for Rundeck, _confluence.admin_user_ and _confluence.admin_password_ are used for confluence, etc.

[source%nowrap,bash]
.application-oauth2.properties
----
# configure technical user for rundeck. Do not authenticate via oauth2, since not implemented.
rundeck.admin_password=rundeck_admin
rundeck.admin_user=rundeck_admin

# configure technical user for bitbucket. Do not authenticate via oauth2, since not implemented.
bitbucket.admin_password=bitbucket_admin
bitbucket.admin_user=bitbucket_admin

# configure technical user for confluence. Do not authenticate via oauth2, since not implemented.
confluence.admin_password=confluence_admin
confluence.admin_user=confluence_admin

# configure technical user for jira. Do not authenticate via oauth2, since not implemented.
jira.admin_password=jira_admin
jira.admin_user=jira_admin
----
[TIP]
Note: if the pair of properties is not defined for a third party tool, the logged in user's credentials are used to authenticate against the application.
The credentials are read by caling the method _getUserName_ and _getUserPassword_ from https://github.com/opendevstack/ods-provisioning-app/blob/master/src/main/java/org/opendevstack/provision/adapter/IODSAuthnzAdapter[IODSAuthnzAdapter]]. See also implementation of _org.opendevstack.provision.services.BaseServiceAdapter#authenticatedCall()_
