apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: prov-app
    name: prov-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: prov-app:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
