apiVersion: v1
kind: Template
objects:
- kind: ConfigMap
  metadata:
    labels:
      app: prov-app
    name: application.properties
  apiVersion: v1
  data:
    properties: |
      #log level
      logging.level.root=WARN
      logging.level.org.springframework=INFO
      logging.level.org.springframework.security=DEBUG
      logging.level.com.atlassian=INFO
      logging.level.com.atlassian.crowd=${LOG_LEVEL_ATLASSIAN_CROWD}
      logging.level.org.opendevstack=${LOG_LEVEL_OPENDEVSTACK}

      #log file
      logging.file=provision.log

      # atlassian API calls take sooo long
      server.servlet.session.timeout=240
      server.connection-timeout=90000
      spring.session.timeout=240
      spring.mvc.async.request-timeout=90000
      
      #server port
      server.port:8080
      server.use-forward-headers=true

      global.keyuser.role.name=${KEYUSER_GROUP}
      # project types, these two are configured in the src/main/resources/application.properties
      project.template.key.names=default,kanban

      #JIRA properties
      jira.uri=${JIRA_URI}
      jira.api.path=/rest/api/latest
      jira.permission.filepattern=classpath*:permission-templates/jira.permission.*

      #JIRA default project templates
      jira.project.template.key=com.pyxis.greenhopper.jira:gh-scrum-template
      jira.project.template.type=software

      # kanban project type
      jira.project.template.key.kanban=com.pyxis.greenhopper.jira:gh-kanban-template
      jira.project.template.type.kanban=software

      #Confluence properties
      confluence.uri=${CONFLUENCE_URI}
      confluence.api.path=/rest
      confluence.json.rpc.api.path=/rpc/json-rpc/confluenceservice-v2
      confluence.permission.filepattern=classpath*:permission-templates/confluence.permission.*

      #Bitbucket properties
      bitbucket.uri=${BITBUCKET_URI}
      bitbucket.api.path=/rest/api/1.0
      bitbucket.repository.pattern=%s-%s
      bitbucket.default.user.group=${CROWD_USER_GROUP}
      bitbucket.technical.user=${CD_USER_ID}

      #openshift properties
      openshift.apps.basedomain=${OPENSHIFT_APPS_BASEDOMAIN}
      openshift.console.uri=${OPENSHIFT_CONSOLE_HOST}/console/project/

      # allow /or disallow a jira only project to be upgraded to a full OCP project
      openshift.project.upgrade=false

      #openshift project name patterns
      openshift.test.project.name.pattern=%s%s-test
      openshift.dev.project.name.pattern=%s%s-dev
      openshift.jenkins.project.name.pattern=jenkins-%s-cd%s
      openshift.jenkins.webhookproxy.name.pattern=webhook-proxy-%s-cd%s
      openshift.jenkins.trigger.secret=${PIPELINE_TRIGGER_SECRET}

      #Rundeck properties
      rundeck.uri=${RUNDECK_URI}
      rundeck.system.path=/rundeck
      rundeck.api.path=/rundeck/api/19
      rundeck.project.name=Quickstarters
      rundeck.group.pattern=${PACKAGE_PREFIX}.%s
      rundeck.artifact.pattern=%s-%s
      rundeck.project.group.quickstarter=quickstarts
      rundeck.project.group.openshift=openshift
      rundeck.project.openshift.create.name=create-projects

      #Cookie Domain
      atlassian.domain=${ATLASSIAN_DOMAIN}

      #Data for confluence space creation
      confluence.blueprint.key=com.atlassian.confluence.plugins.confluence-space-blueprints:documentation-space-blueprint

      #crowd properties
      crowd.local.directory=LocalDirectory
      crowd.application.name=provision
      crowd.application.password=${CROWD_PASSWORD}
      crowd.server.url=${CROWD_URL}/crowd/services/
      crowd.cookie.domain=${OPENSHIFT_APPS_BASEDOMAIN}
      crowd.user.group=${CROWD_USER_GROUP}
      crowd.admin.group=${CROWD_ADMIN_GROUP}
      
      # crowd sso cookie keyname
      crowd.sso.cookie.name=crowd.token_key

      #local storage
      project.storage.local=/opt/provision/history/

      jasypt.encryptor.password=${JASYPT_PASSWORD}

      #mail properties
      
      # enable mail sendout with project details
      mail.enabled=true
      
      spring.mail.host=${MAIL_HOST}
      spring.mail.port=587
      spring.mail.protocol=smtp
      spring.mail.debug=true
      spring.mail.defaultEncoding=UTF-8
      spring.mail.smtp.timeout=1000
      spring.mail.smtp.connectiontimeout=1000
      spring.mail.smtps.connectiontimeout=1000
      spring.mail.properties.mail.smtp.ssl.enable=true
      spring.mail.properties.mail.smtp.auth=true
      spring.mail.username=${MAIL_USERNAME}
      spring.mail.password=${MAIL_PASSWORD}
      provison.mail.sender=provision@${MAIL_HOST}
parameters:
- name: JIRA_URI
  required: true
  description: the URI of JIRA used to create new jira projects  
- name: CONFLUENCE_URI
  required: true
  description: the URI of confluence used to create new confluence spaces
- name: BITBUCKET_URI
  required: true
  description: the URI of bitbucket used to create new project and repositories  
- name: RUNDECK_URI
  required: true
  description: the URI of rundeck used to kickstart provisioning projects and components  
- name: CROWD_URL
  required: true
  description: the URI of crowd used to authenticate users from the app against    
- name: OPENSHIFT_API_HOST
  required: true
  description: the API host of the OCP cluster   
- name: OPENSHIFT_CONSOLE_HOST
  required: true
  description: the console host of the OCP cluster 
- name: CROWD_USER_GROUP
  required: true
  description: crowd user group     
- name: CD_USER_ID
  required: true
  description: the username of the CD user     
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
  description: the domain of routes exposed on OCP   
- name: PACKAGE_PREFIX
  required: true
  description: the default package prefix   
- name: ATLASSIAN_DOMAIN
  required: true
  description: the domain of the atlassian toolsuite needed for single signon cookies  
- name: CROWD_PASSWORD
  required: true
  description: password of the crowd app to authenticate the provision app against
- name: JASYPT_PASSWORD
  required: true
- name: MAIL_HOST
  required: true
  description: The hostname of the mailserver
- name: MAIL_PASSWORD
  required: true
  description: The password to authenticate against the mail server
- name: MAIL_USERNAME
  required: true
  description: The username to authenticate against the mail server
- name: CROWD_ADMIN_GROUP
  required: true
  description: The crowd admin group name
- name: KEYUSER_GROUP
  required: true
  description: The keyuser group name as in crowd used when creating a new permission scheme
- name: PIPELINE_TRIGGER_SECRET
  required: true
  description: The trigger secret to pass to the webhook proxy
- name: LOG_LEVEL_ATLASSIAN_CROWD
  required: true
  description: Log level of Atlassian crowd package
- name: LOG_LEVEL_OPENDEVSTACK
  required: true
  description: Log level of OpenDevStack package
