apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: prov-app
    name: prov-app
  spec:
    replicas: 1
    selector:
      app: prov-app
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: prov-app
      spec:
        containers:
        - image: ${TAILOR_NAMESPACE}/prov-app:${ODS_VERSION}
          imagePullPolicy: IfNotPresent
          name: prov-app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 3Gi
            requests:
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /opt/provision/history
            name: volume-history
          - mountPath: /config
            name: volume-ikfik
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: volume-history
          persistentVolumeClaim:
            claimName: prov-history
        - configMap:
            defaultMode: 420
            items:
            - key: properties
              path: application.properties
            name: application.properties
          name: volume-ikfik
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - prov-app
        from:
          kind: ImageStreamTag
          name: prov-app:${ODS_VERSION}
          namespace: ${TAILOR_NAMESPACE}
      type: ImageChange
    - type: ConfigChange
parameters:
- name: TAILOR_NAMESPACE
  required: true
- name: ODS_VERSION
  required: true
