apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: prov-app
    name: prov-app
  spec:
    dockerImageRepository: prov-app
    lookupPolicy:
      local: false
