apiVersion: v1
kind: Template
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: cd-user-token
    labels:
      app: prov-app
  type: kubernetes.io/basic-auth
  data:
    password: ${CD_USER_PWD}
parameters:
- name: CD_USER_PWD
  description: cd_user password (base64 encoded)
  required: true
