apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-test
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: prov-app
      component: prov-app
      env: test
      template: bc-docker
    name: prov-app
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: prov-app:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      dockerStrategy: {}
      type: Docker
    triggers: []
