apiVersion: v1
kind: Template
metadata:
  annotations: {}
  creationTimestamp: null
  name: prov-app-test
objects:
- apiVersion: v1
  kind: Route
  metadata:
    annotations: {}
    creationTimestamp: null
    labels:
      app: prov-app
      component: prov-app
      env: test
      template: component-route-template
    name: prov-app
  spec:
    host: prov-app-test${OPENSHIFT_APPS_BASEDOMAIN}
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: prov-app
      weight: 100
    wildcardPolicy: None
parameters:
- name: OPENSHIFT_APPS_BASEDOMAIN
  required: true
